### ISSUE TITLE
Registering with mail.

### ISSUE THREAD

**Issue by GustavHandmark** [FranzGithub/etsn05-samakning#24]
When trying to register with and email with underscores ( _ ) you get an alert window telling you to please match the requested format.

**Comment by GustavHandmark** [comment]
Ah maybe it's every email that doesn't end in gmail.com ? And we're only allowing gmail adresses?

**Comment by jadlers** [comment]
@GustavHandmark That's correct. Valid email addresses are, according to [SRS 6.3.4](https://docs.google.com/document/d/1ZvEyOamG2U_Pa69U69RykN-T4ngIZo7kiV_Avaz8eoQ/edit#heading=h.kg1wq681oc7x), "En mailadress skall vara enligt det reguljära uttrycket [a-zA-Z0-9.]{1,20}@gmail.com". Underscore are therefore not valid, and we're also only allowing gmail addresses

**Comment by GustavHandmark** [comment]
Perfect, closing.
